drivers: rosy: touchscreen: Add missing gesture preprocessor directives
Fixes:
error: 'ft8006m_gesture_data' undeclared
error: 'gesture_data' undeclared

Signed-off-by: Dimitar Yurukov <mscalindt@protonmail.com>